# Generated by Django 4.1.6 on 2023-04-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="category",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "前端"), (2, "后端"), (3, "项目相关"), (4, "其他")],
                null=True,
                verbose_name="文章分类",
            ),
        ),
    ]
